#!/usr/bin/env bash

##
# Default configuration
#

# the actual tee command
teebin=tee

# redirect to shared memory filesystem
tmpdir=/dev/shm/teemp.$USER

# file path mangle function
mangler=shasum
# interesting bytes in the mangle function output (GNU cut 'LIST' style)
manglebytes=1-40

##
# Read configuration files
#

# read system configuration
if [ -r /etc/.teemp ]; then 
  # bash 4.0 only
  #source <(egrep -o '^(teebin|tmpdir|mangler|manglebytes)=.*' $PWD/.teemp)
  source /dev/stdin <<< $(egrep -o '^(teebin|tmpdir|mangler|manglebytes)=.*' /etc/.teemp)
fi

# read user configuration
if [ -r $HOME/.teemp ]; then
  source /dev/stdin <<< $(egrep -o '^(teebin|tmpdir|mangler|manglebytes)=.*' $HOME/.teemp)
fi

# read local configuration
if [ -r $PWD/.teemp ]; then
  source /dev/stdin <<< $(egrep -o '^(teebin|tmpdir|mangler|manglebytes)=.*' $PWD/.teemp)
fi

##
# TEEMP
#

# arguments parsing
OPTIND=1
while getopts "hb:d:m:x:" OPTION
do
  case $OPTION in
  h) 
    echo USAGE: teemp [OPTION]... [FILE]...
    echo
    echo '   -h    show this message'
    echo '   -b    sets manglebytes'
    echo '   -d    sets tmpdir'
    echo '   -m    sets mangler'
    echo '   -x    sets teebin'
    echo
    echo 'Written by Quentin Sabah.'
    exit 0
    ;;

  d)
    tmpdir=$OPTARG
    ;;

  m)
    mangler=$OPTARG
    ;;

  b)
    manglebytes=$OPTARG
    ;;
  
  x)
    teebin=$OPTARG
    ;;
  esac
done
shift $(($OPTIND - 1))

mkdir -p $tmpdir

for file in $*
do
  case $file in
  -*)
    ;;

  *)
    dirn=$(dirname $file)
    basen=$(basename $file)
    absfile=$(cd $dirn && echo $PWD/$basen)
    
    tmpfile=$(echo $absfile | $mangler | cut -b $manglebytes)
    touch $tmpdir/$tmpfile
    ln -f -s $tmpdir/$tmpfile $absfile
    ;;
  esac
done

exec $teebin $*
exit 128
